base_url = "https://nalog.dev"
title = "nalog"
description = "物理シミュレーション・ゲーム開発などの技術メモ"
default_language = "ja"
compile_sass = false
minify_html = false
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown.highlighting]
theme = "ayu-dark"

[extra]
author = "nalog"
r2_base_url = "https://assets.nalog.dev"

[[taxonomies]]
name = "tags"
feed = true
paginate_by = 10
